// Environment variable configuration and validation.
// REQUIRED vars have no safe default and must be set before starting.
// All other vars have conservative defaults suitable for first-run operators.
export const ENV = {
    // true when NODE_ENV is not "production"
    isDev: process.env.NODE_ENV !== "production",
    // Set DEBUG=1 or DEBUG=true to enable verbose console output
    debug: process.env.DEBUG === "1" || process.env.DEBUG === "true",

    // "mainnet" | "testnet" | "regtest"
    bitcoinNetwork: process.env.BITCOIN_NETWORK || "mainnet",
    // gRPC address of the LND node; on Umbrel this is the lightning service IP
    lndGrpcHost: process.env.LND_GRPC_HOST || "lightning_lnd_1:10009",
    // REQUIRED: compressed public key of the treasury node (33-byte hex, 66 chars).
    // If unset, no node will be identified as treasury and all treasury endpoints
    // will return 403.
    treasuryPubkey: process.env.TREASURY_PUBKEY || "",

    // --- Rate limits (member payment API) ---
    // Grain transactions can exceed $20k (~30M sats at current prices).
    // Defaults sized for agricultural commerce, not micro-payments.
    // Max payments per member per minute
    rateLimitTxPerMinute: parseInt(process.env.RATE_LIMIT_TX_PER_MINUTE || "10", 10),
    // Max sats per member per minute
    rateLimitSatsPerMinute: parseInt(process.env.RATE_LIMIT_SATS_PER_MINUTE || "50000000", 10),
    // Max sats per member per hour
    rateLimitSatsPerHour: parseInt(process.env.RATE_LIMIT_SATS_PER_HOUR || "200000000", 10),
    // Max sats in a single payment
    rateLimitMaxSinglePayment: parseInt(process.env.RATE_LIMIT_MAX_SINGLE_PAYMENT || "50000000", 10),

    // --- Rebalance viability thresholds ---
    // Minimum remote/capacity ratio (ppm) on the incoming channel to attempt rebalance
    rebalanceMinIncomingRemoteRatioPpm: Number(
        process.env.REBALANCE_MIN_INCOMING_REMOTE_RATIO_PPM ?? "200000"
    ),
    // Minimum local/capacity ratio (ppm) on the outgoing channel to attempt rebalance
    rebalanceMinOutgoingLocalRatioPpm: Number(
        process.env.REBALANCE_MIN_OUTGOING_LOCAL_RATIO_PPM ?? "200000"
    ),
    // Sats to keep back from available liquidity when sizing a rebalance
    rebalanceSafetyBufferSats: Number(process.env.REBALANCE_SAFETY_BUFFER_SATS ?? "1000"),

    // --- Rebalance scheduler ---
    // Set to "true" to enable the automated rebalance scheduler (default: off)
    rebalanceSchedulerEnabled: process.env.REBALANCE_SCHEDULER_ENABLED === "true",
    // Set to "true" to run the scheduler in dry-run mode (logs decisions, no LND calls)
    rebalanceSchedulerDryRun: process.env.REBALANCE_SCHEDULER_DRY_RUN === "true",
    // How often the scheduler ticks, in milliseconds (default: 60s)
    rebalanceSchedulerIntervalMs: Number(
        process.env.REBALANCE_SCHEDULER_INTERVAL_MS ?? "60000"
    ),
    // Default rebalance amount in sats per automated run
    rebalanceDefaultTokens: Number(process.env.REBALANCE_DEFAULT_TOKENS ?? "5000"),
    // Hard ceiling on rebalance amount in sats (caps scheduler and manual requests)
    rebalanceMaxTokens: Number(process.env.REBALANCE_MAX_TOKENS ?? "25000"),
    // Max fee in sats the scheduler will pay for a single rebalance
    rebalanceDefaultMaxFeeSats: Number(
        process.env.REBALANCE_DEFAULT_MAX_FEE_SATS ?? "10"
    ),
    // Max fee-to-amount ratio in ppm the scheduler will tolerate (default: 1000 = 0.1%)
    rebalanceMaxFeePpm: Number(process.env.REBALANCE_MAX_FEE_PPM ?? "1000"),
    // Minimum minutes between two successful automated rebalances
    rebalanceCooldownMinutes: Number(process.env.REBALANCE_COOLDOWN_MINUTES ?? "30"),

    // --- Cluster rebalance engine v1 (LEGACY — gated off by default; retained for code reference) ---
    // Set to "true" to enable the cluster-based rebalance engine (fee steering +
    // circular rebalance + topology monitor). Not part of steady-state operation
    // under the role-based rebalancing model — see `docs/ARCHITECTURE.md`
    // § Liquidity Management.
    clusterRebalanceEnabled: process.env.CLUSTER_REBALANCE_ENABLED === "true",
    // Interval between cluster rebalance runs in milliseconds (default: 15 min)
    clusterRebalanceIntervalMs: Number(
        process.env.CLUSTER_REBALANCE_INTERVAL_MS ?? "900000"
    ),

    // --- Loop (submarine swaps via Bitcorn's litd sidecar in remote-LND mode) ---
    // litd runs Loop as an integrated subserver, connected to LND remotely.
    // ARM64-compatible (standalone loopd images have broken ARM builds).
    loopGrpcHost: process.env.LOOP_GRPC_HOST || "bitcorn-lightning-node_loopd_1",
    // gRPC port — litd unified HTTPS/gRPC endpoint
    loopGrpcPort: Number(process.env.LOOP_GRPC_PORT ?? "8443"),
    // TLS certificate generated by litd
    loopTlsCertPath: process.env.LOOP_TLS_CERT_PATH || "/loop-data/.lit/tls.cert",
    // Loop macaroon for authentication
    loopMacaroonPath: process.env.LOOP_MACAROON_PATH || "/loop-data/.loop/mainnet/loop.macaroon",
    // Max swap fee as a percentage of the swap amount.
    // Loop has a ~30k sat fixed prepay component, so small swaps (250k) have ~12% effective fee.
    // Default 15% accommodates the fixed cost; larger swaps have much lower effective rates.
    loopMaxSwapFeePct: Number(process.env.LOOP_MAX_SWAP_FEE_PCT ?? "15"),
    // Max miner fee in sats for the on-chain sweep (default: 20,000)
    loopMaxMinerFeeSats: Number(process.env.LOOP_MAX_MINER_FEE_SATS ?? "20000"),
    // Minimum sats to rebalance via Loop Out (default: 50,000)
    loopMinRebalanceSats: Number(process.env.LOOP_MIN_REBALANCE_SATS ?? "50000"),
    // On-chain confirmation target for the sweep transaction (default: 6 blocks)
    loopConfTarget: Number(process.env.LOOP_CONF_TARGET ?? "6"),

    // --- Coinbase Onramp ---
    // Required to build Onramp URLs. Get from Coinbase Developer Platform.
    // If unset, GET /api/coinbase/onramp-url returns 503.
    coinbaseAppId: process.env.COINBASE_APP_ID || "",
    // Cloudflare Worker URL that generates Coinbase Onramp session tokens.
    // If unset, GET /api/coinbase/onramp-url returns coinbase_not_configured.
    coinbaseWorkerUrl: process.env.COINBASE_WORKER_URL || "",

    // --- BASE sync loop (spec §7) ---
    // Number of blocks to wait before considering a Settled event safely
    // committed for event-sync purposes. Spec §7.4 + T7 recommend 64 blocks
    // (~2 minutes at BASE's 2-second block time). Testnet dev can override
    // to a lower value (e.g. 12) for faster iteration; production should
    // use the default 64.
    baseConfirmationDepth: Number(process.env.BASE_CONFIRMATION_DEPTH ?? "64"),

    // --- Valuation manual input (treasury → Worker HMAC-signed submissions) ---
    // Base URL of the Cloudflare Worker that accepts POST /valuation/manual.
    // Defaults to COINBASE_WORKER_URL since both endpoints live on the same
    // Worker; override if they ever split. If unset, POST /api/valuation/manual
    // returns 503 valuation_worker_not_configured.
    valuationWorkerUrl: process.env.VALUATION_WORKER_URL || process.env.COINBASE_WORKER_URL || "",
    // Shared HMAC secret between this treasury API and the Worker. Must match
    // the VALUATION_SUBMIT_HMAC set on the Worker via `wrangler secret put`.
    // If unset, POST /api/valuation/manual returns 503.
    valuationSubmitHmac: process.env.VALUATION_SUBMIT_HMAC || "",

    // --- Coinbase Auto-Buy Executor ---
    // Global kill switch. When false, the scheduler refuses to create any
    // scheduled rows. Default false so a fresh install doesn't start buying
    // until the operator explicitly enables via POST /api/autobuy/enable.
    autoBuyEnabled: process.env.AUTOBUY_ENABLED === "true",
    // Max USD per single scheduled buy. Caps the result of
    // base_unit × multiplier. Row transitions to skipped_cap_hit on breach.
    autoBuyMaxSingleBuyUsd: Number(process.env.AUTOBUY_MAX_SINGLE_BUY_USD ?? "1000"),
    // Rolling 7-day cap on filled_usd across all completed runs.
    autoBuyMax7dUsd: Number(process.env.AUTOBUY_MAX_7D_USD ?? "2000"),
    // Rolling 30-day cap.
    autoBuyMax30dUsd: Number(process.env.AUTOBUY_MAX_30D_USD ?? "5000"),
    // Max base_unit the user can set via PATCH /api/autobuy/config.
    // Prevents a UI typo from setting $1,000,000 as the base.
    autoBuyBaseUnitMaxUsd: Number(process.env.AUTOBUY_BASE_UNIT_MAX_USD ?? "500"),
    // If the Worker's /valuation/current.updated_at is older than this many
    // hours, the scheduler refuses to buy (row → skipped_stale_data).
    autoBuyStaleDataMaxHours: Number(process.env.AUTOBUY_STALE_DATA_MAX_HOURS ?? "48"),
    // Auto-pause after N consecutive failed_buy or failed_withdraw transitions.
    // Operator must click Resume to re-enable. Reset on any successful sweep.
    autoBuyFailurePauseThreshold: Number(process.env.AUTOBUY_FAILURE_PAUSE_THRESHOLD ?? "3"),

    // --- Member swap / withdrawal limits ---
    // Minimum sats a member can withdraw via Loop Out (default: Loop minimum = 250,000)
    memberMinWithdrawalSat: Number(process.env.MEMBER_MIN_WITHDRAWAL_SAT ?? "250000"),
    // Maximum sats a member can withdraw in a single Loop Out (default: 2,000,000)
    memberMaxWithdrawalSat: Number(process.env.MEMBER_MAX_WITHDRAWAL_SAT ?? "2000000"),
    // Maximum total daily withdrawal for a member (default: 5,000,000)
    memberMaxDailyWithdrawalSat: Number(process.env.MEMBER_MAX_DAILY_WITHDRAWAL_SAT ?? "5000000"),
    // Quote expiry in seconds (default: 5 minutes)
    swapQuoteExpirySec: Number(process.env.SWAP_QUOTE_EXPIRY_SEC ?? "300"),
    // Safety buffer subtracted from member's treasury-channel local balance (default: 50,000)
    // Prevents routing failures from razor-thin margins
    swapMemberRoutingBufferSat: Number(process.env.SWAP_MEMBER_ROUTING_BUFFER_SAT ?? "50000"),
    // Reserve buffer subtracted from treasury external egress capacity (default: 100,000)
    // Ensures treasury retains minimum outbound on egress channels
    swapTreasuryEgressReserveSat: Number(process.env.SWAP_TREASURY_EGRESS_RESERVE_SAT ?? "100000"),

    // --- Member refill (Loop In) limits ---
    // Comma-separated list of Loop swap server pubkeys for route-probe preflight.
    // Default: Lightning Labs mainnet Loop server.
    loopServerPubkeys: (process.env.LOOP_SERVER_PUBKEYS || "021c97a90a411ff2b10dc2a8e32de2f29d2fa49d41bfbb52bd416e460db0747d0d")
        .split(",").map(s => s.trim()).filter(Boolean),
    // Minimum sats a member can refill via Loop In (default: 100,000)
    memberMinRefillSat: Number(process.env.MEMBER_MIN_REFILL_SAT ?? "100000"),
    // Maximum sats a member can refill in a single Loop In (default: 3,000,000)
    memberMaxRefillSat: Number(process.env.MEMBER_MAX_REFILL_SAT ?? "3000000"),
    // Maximum total daily refill for a member (default: 5,000,000)
    memberMaxDailyRefillSat: Number(process.env.MEMBER_MAX_DAILY_REFILL_SAT ?? "5000000"),
    // On-chain reserve buffer — subtracted from available balance to prevent draining to zero
    memberOnchainReserveSat: Number(process.env.MEMBER_ONCHAIN_RESERVE_SAT ?? "50000"),

    // --- Subscription rail tier enforcement (Stage 3+) ---
    // Tier 2 routing-gate: when true, payInvoice and invoice-generation
    // routes refuse to act for members whose current_tier ∈
    // {prepay, routing_lapsed, close_due}. Default: true (the wiring
    // ships enabled per spec §10 step 6 "feature-flag-able"; set to
    // "false" to disable the gate without code changes).
    subscriptionTier2Enabled: process.env.SUBSCRIPTION_TIER2_ENABLED !== "false",
    // Tier 3 cooperative-close scheduler: when false (default), runs in
    // dry-run mode and only structured-logs "would close" events. When
    // true, actually issues LND CloseChannel calls. Per spec §10 step 7,
    // promotion to live happens at Stage 6 after a ≥60-day observation
    // of the dry-run behaviour.
    subscriptionTier3Live: process.env.SUBSCRIPTION_TIER3_LIVE === "true",
    // Cadence for the Tier 3 dry-run scheduler tick. 5 min default per
    // spec §5.3 — the scheduler iterates members in close_due tier and
    // logs (or, when live, issues) cooperative-close actions.
    subscriptionTier3IntervalMs: Number(
        process.env.SUBSCRIPTION_TIER3_INTERVAL_MS ?? String(5 * 60 * 1000)
    ),
    // Where the member node should POST /api/subscription/token to
    // refresh its entitlement JWT. On treasury nodes leave this unset
    // (the refresh scheduler falls back to localhost and the /token
    // endpoint's self-mint carve-out issues a full-scope token for the
    // treasury). On member nodes this must point at the treasury's
    // reachable API URL (e.g., http://<treasury-tailnet-ip>:3101).
    // Unset on a member node → refresh logs a warning and skips; the
    // member operates without an entitlement token until configured.
    treasuryApiUrl: process.env.TREASURY_API_URL || "",
};
