services:
  api:
    image: ghcr.io/ethancail/bitcorn-lightning-application/api:1.2.1
    restart: unless-stopped
    ports:
      - "3101:3101"
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/lnd:ro
    environment:
      BITCOIN_NETWORK: ${BITCOIN_NETWORK:-mainnet}
      LND_GRPC_HOST: 10.21.21.9:10009
      TREASURY_PUBKEY: 02b759b1552f6471599420c9aa8b7fb52c0a343ecc8a06157b452b5a3b107a1bca
      COINBASE_APP_ID: 1cebd598-0a9d-4567-8603-8ef051fd1101
      COINBASE_WORKER_URL: "https://bitcorn-onramp.ethancail.workers.dev"
    networks:
      - umbrel

  web:
    image: ghcr.io/ethancail/bitcorn-lightning-application/web:1.2.1
    restart: unless-stopped
    ports:
      - "3200:3200"
    depends_on:
      - api
    networks:
      - umbrel

networks:
  umbrel:
    external: true
    name: umbrel_main_network
